# Generated by Django 4.0.4 on 2022-05-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='number_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('in stock', 'в наличии'), ('out of stock', 'нет в наличии')], default='нет в наличии', max_length=20),
        ),
    ]
